### ISSUE TITLE
Fractions Intro Master Checklist

### ISSUE THREAD

**Issue by veillette** [phetsims/fractions-intro#1]
Since this sim is almost an exact copy of the Java version (in terms of look and functionality), the Java sim in essence is serving as the design spec, although the code is basically being written from scratch. Thus multiple parts of the checklist have been removed.

## Design
- [x] **Sim folder and design doc created** (Date: 06/22/2017) 
  - [x] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [x] Place design doc in the sim folder
- [x] **Legacy sim docs/info gathered**
  - [x] Sim suggestions doc reviewed
  - [x] Unfuddle tickets reviewed
- [x] **Learning goals and standards identified** (Date: //)
- [x] **Features for PhET-iO discussion** - N/A
- [x] **Lead designer "sign off"** (Date: //) 
  - [x] Performance acceptable
  - [x] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [x] **Pre-publication items** 
  - [x] Main screenshot (2048x1344, PNG, 32-bit color, browser chrome stripped)
  - [x] Auxilary screenshots (up to 3 additional)
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Teacher Guide created, uploaded, and added to sim design folder
  - [x] Add an activity
  - [x] Verify credits
- [x] **Post-publication items** 
  - [x] Sim primer issue
  - [x] Hold postmortem if applicable (Date: //)  - N/A

## Implementation
- [x] **Repository created** (Date: 05/09/2017)
  - [x] simula-rasa used to create project skeleton
  - [x] README.md created using `grunt unpublished-readme`
  - [x] Collaborators added (such as QA team, designers, etc)
  - [x] standard GitHub label set applied
  - [x] repository added to chipper/data/ filesr
  - [x] Port existing strings (IF ANY) and commit to the GitHub repo (auto-ported strings from Java and Flash sims can
  be found in babel/autoport). The strings should be deleted from babel/autoport and @jbphet should immediately be asked
  to pull from rosetta to avoid conflicts.
- [x] **Development started** (Date: 03/19/2018)
- [x] **Sim is "feature complete"** (Date: 12/15/2018)
- [x] **Code review completed** (Date: 12/24/2018) 
- [x] **Pre-publication items** 
  - [x] Main screenshot (2048x1344, PNG, 32-bit color, browser chrome stripped)
  - [x] Verify credits
- [x] **Published** (Date: 01/29/2019) 
  - [x] README.md updated using `grunt published-README` (in master and release branch)
  - [x] Mark the sim as published in [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)

## QA
- [x] **Dev testing complete** (Date: 01/08/2019) 
- [x] **First RC published** (Date: 01/16/2019)
  - [x] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [x] **RC testing completed** (Date: 01/28/2019)

**Comment by samreid** [comment]
I've reserved issue #1 for the master checklist, and moved the code review checklist to issue #2.

**Comment by jonathanolson** [comment]
Sim has been published. I filled out the implementation section. @ariel-phet should this be closed or filled out?
