### ISSUE TITLE
PROTO: ToDo List: Proto to Master

### ISSUE THREAD

**Issue by davisv7** [phetsims/fractions-intro#68]
The following is a prioritized checklist of changes to get us started with transitioning proto branch of Fractions-Into to become master branch. Each item will have its own separate issue(s). 

- [x] Add annotations to the protomodel. (see #70 )
- [x] Properties in the protomodel without listeners should be changed to attributes.  (see #71)
- [x] Protomodel should handle initial property values different from hard-coded defaults. (see #69 )
- [x] Max spinner enable/disable property should allow the decreasing of max value until max = 1. (see #74)
- [x] Animation of cells from container to bucket when max decreased. (see #75)
- [x] Protoview of rectangle/circle should indicate denominator (line separators). (see #76)
- [ ] Dedup repeated code (deserves 3-4 separate issues). (see #73)
- [x] Beaker cells should animate from a cell to the bucket when numerator is decreased. (see #67)
- [ ] Beaker cells should animate from the bucket to a cell when the numerator is increased. (see #67)
- [x] JSDocs should be added to the modules.
- [x] Refactor to get rid of proto. (see #72)
